Repository DFHack/dfhack, pull requests merged in 2021-08, with the labels that each got.

#1916 [Core] clear modstate on window focus
  docs/changelog.txt
  library/Core.cpp
Labels: internal

#1924 Documentation: Compilation instructions update for Apple Silicon
  docs/Compile.rst
Labels: documentation

#1934 [test] migrate existing tests to use expect.str_find()
  test/library/gui/dwarfmode.lua
  test/library/print.lua
Labels: tests
