Repository DFHack/dfhack, pull requests merged in 2022-06, with the labels that each got.

#2196 check for files, not md5 receipt in download-df.sh
  .github/workflows/build.yml
  ci/download-df.sh
Labels: ci

#2203 Update eventful.lua
  docs/Lua API.rst
  docs/changelog.txt
  plugins/lua/eventful.lua
Labels: eventful

#2208 Add myself to Authors.rst
  docs/Authors.rst
Labels: documentation

#2193 ensure our docs build cleanly with sphinx-5
  conf.py
  docs/styles/sphinx5.css
Labels: documentation, ci
