Repository DFHack/dfhack, pull requests merged in 2022-03, with the labels that each got.

#2041 Reword the titles of the various guides
  docs/guides/examples-guide.rst
  docs/guides/quickfort-alias-guide.rst
  docs/guides/quickfort-library-guide.rst
  docs/guides/quickfort-user-guide.rst
Labels: documentation

#2053 Typo Fix in dig.cpp
  plugins/dig.cpp
Labels: documentation

#2059 fix crash in eventful due to misaligned fn map
  library/include/modules/EventManager.h
  plugins/eventful.cpp
Labels: crash/hang

#2060 [core] Debug logging facelift
  library/Core.cpp
  library/Debug.cpp
  library/include/Debug.h
  library/include/DebugManager.h
  plugins/debug.cpp
Labels: internal

#2062 Bump max GCC in GitHub Actions build matrix to 11
  .github/workflows/build.yml
Labels: ci

#2061 git-describe: fail earlier if git fails to run or doesn't exist
  library/git-describe.cmake.in
Labels: build

#2051 [manipulator] Tweak colors to make cursor easier to locate
  docs/changelog.txt
  plugins/manipulator.cpp
Labels: manipulator

#2068 Buildmaster rebuild action
  .github/workflows/buildmaster-rebuild.yml
  ci/buildmaster-rebuild-pr.py
Labels: build
